### ISSUE TITLE
Ability to generate clean database snapshots for test harness execution

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1034]
## Description
As a QA I want to be able to have a clear base state for the integration tests

## Acceptance criteria

- [ ] Script that when run creates a database snapshot 
- [ ] Clear structure / naming for how database snapshots (base state) are stored in version control
- [ ] Extend populator to have a flag to create the ecoverse if it is not already present

Note: this script generates the file which the QA / other user can then commit into version control.

## Additional Context

- create-snapshot.sh with the following steps
- drop alkemio schema
- create alkemio schema
- run migrations
- run populator with configurable ods file
- create snapshot

**Comment by Comoque1** [comment]
The mechanism for dropDB / createDB / runMigrations/ runPopulator / createSnapshot  is in place.
Missing part is to have the default bootstrap users, after the DB drop/create is performed. This prevents successful creation of entities. It will be addressed in a separate issue.
