### ISSUE TITLE
BUG: Creating reference on context is failing, when executed as separate mutation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1042]
**Describe the bug**
Creating reference on context is failing, when executed as separate mutation.

**To Reproduce**
1. Go to http://localhost:4000/graphql
2. Create a challenge with context and reference within the context
3. From the created context take the contextID and create new referenceOnContext **with the same reference name as the one created as part of the challenge**
```
mutation createReferenceOnContext(
  $referenceInput: CreateReferenceOnContextInput!
) {
  createReferenceOnContext(referenceInput: $referenceInput) {
    id
    name
    uri
  }
}
```
{
  "referenceInput": {
    "contextID": "208cba4f-f18a-4293-928c-d20e7257f550",
    "description": "ksdhfjk",
    "name": "test7",
    "uri": "khdskfj"
  }
}
4. Reference is not created, error is thrown: ```
"message": "Authorization: unable to grant 'create' privilege: create reference on context: 208cba4f-f18a-4293-928c-d20e7257f550",
      "locations": 
```
Note:
The created references as part of challenge creation, doesn't have `authorisationId`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0945d232-6783-408c-8d6c-d358105a1c1b)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/977089b9-bf0a-485b-9f4e-36f870b07b6a)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3cf3b681-591b-418b-b449-74a919227ace)


**Expected behavior**
References are created successfully on context.

**Comment by techsmyth** [comment]
Just tried to reproduce and could not. 

Can you please:
- state the user that you were logged in as
- capture the log file that was shown on the server console when in verbose debug mode with console logging enabled?

**Comment by Comoque1** [comment]
Account used for the login: admin@cherrytwist.org
Creating a reference on Context works for me, with latest develop branch, as well.

Updated "repro steps" - the new reference that is intended to be created is with the same name, as the referenceName part of the challenge.

Below are screenshots from bug description:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dfcc9f19-00fd-4466-be8a-f13e948b09d2)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/419a5649-2da1-4bf1-a096-bbde26f69f44)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/913ab218-90ec-4864-b781-52692317c4bf)

The new error that I get, when try to create reference with same name is: `"message": "Authorization: no definition provided",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8a81f0c5-56b5-4ace-a508-0872e22106c5)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/213d178f-d6c9-4b29-8192-7f6171b1f234)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0edc0db8-b8ec-4f40-b944-5bbd9154f0be)

What seems, that need to be addressed is:
1. When create reference as part of challenge creation mutation, the reference, should get `authorisationId`.
2. When try to create reference on same context and using the same name as of already existing one, should throw an error message, that reference with such name already exists.

**Comment by Comoque1** [comment]
After the latest changes is tested - OK
Once changes are merged - to be closed.
