### ISSUE TITLE
BUG: Deleting user application is throwing error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1043]
**Describe the bug**
Deleting user application is throwing error, for deleting community that doesn't exist.

**To Reproduce**
1. Go to http://localhost:4000/graphql
2.Create an application
3. Delete the application: error is thrown:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4ff8ffa2-e81c-4c56-bf6e-f48d676928ef)

**Expected behavior**
Deleting an application, must be successful.

**Comment by Comoque1** [comment]
The issue is still reproducible.
When I provide `applicationId`, to the `deleteApplication` mutation, it is considered as `communityId`, instead of `applicationId`.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fd2859aa-67d2-4079-9747-33daab69a9ba)

Reopened.

**Comment by techsmyth** [comment]
Am very puzzled, it really looks to be sorted on develop. Lets touch base tomorrow...

**Comment by Comoque1** [comment]
Closing. 
The version I have tested it above, didn't contain the latest changes.
