### ISSUE TITLE
BUG: Changing event on an application is failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1044]
**Describe the bug**
Changing event on an application is failing.

**To Reproduce**
1. Go to http://localhost:4000/graphql
2. Create application
3. Perform the following mutation for the created application
```
mutation eventOnApplication($applicationEventData: ApplicationEventInput!) {
      eventOnApplication(applicationEventData: $applicationEventData) {
    lifecycle{
      id
      state
      nextEvents
    }
  }
}
```
```
{
  "applicationEventData": {
    "applicationID": "a10fcdf7-6113-48b3-8244-251060d4e0a2",
    "eventName": "REJECT"
  }
}
```
4. See error - error that, such epplication doesn't exist is thrown.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/770fe0e5-a9ef-41f0-9ac6-19ff32b0e37d)

**Expected behavior**
Application event is changed successfully.

**Comment by techsmyth** [comment]
Just tried this locally and it was working fine, can you give more details / try it again? 

It looks like the wrong id has been specified, it does need to be the application ID. Can you show the screen show from the application creation?

**Comment by Comoque1** [comment]
Not reproducible anymore.
Closing the issue.
