### ISSUE TITLE
BUG: Server in docker-compose setup is broken

### ISSUE THREAD

**Issue by pimotte** [alkem-io/server#1069]
**Describe the bug**
Networking in the docker-compose doesn't work as it should. Temporary workaround: Running the server outside of docker. Running the dependencies in compose works fine.

**To Reproduce**
1. Start docker-compose setup with `quickstart-server.yaml` included
2. Start client
3. Visit client
4. See bugs (context is null)

**Comment by Comoque1** [comment]
After trying to reproduce, it appears, that the server is not responding at all.
