### ISSUE TITLE
BUG: User cannot create application

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1086]
**Describe the bug**
Non ecoversse user cannot create application to ecoverse community.

**To Reproduce**
1. Go to http://localhost:4455/admin/graphql
2. Perform the following mutation:
```
mutation createApplication($applicationData: CreateApplicationInput!) {
  createApplication(applicationData: $applicationData) {
    id
    user {
      id
      nameID
    }
  }
}
```
```
{
  "applicationData": {
    "parentID": "a5419f10-b354-4546-a058-42448772e066",
    "userID": "a4107adf-6a71-44de-a624-1caf512bd92a",
    "questions": [{ "name": "Test Question 1", "value": "Test answer" }]
  }
}
```

3. Error is thrown: `"message": "Authorization: unable to grant 'update' privilege: create application community: Default Ecoverse",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/952b4216-f29b-49e5-88dd-5f132c1c6d6a)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a8d41fef-1558-4225-b501-26ce10be3f26)

**Expected behavior**
User must be able to create application.

**Comment by techsmyth** [comment]
Looking at the screenshot above, it looks like the user is not registered and thus cannot make an application to join an ecoverse:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2f4b285c-18a8-4acf-a653-6726c54c179c)

**Comment by Comoque1** [comment]
The same happens, when for the user is returned  "AgentInfo"
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6f3f5211-bc8d-4862-a7db-6ad2dcd0fc85)

**Comment by Comoque1** [comment]
Tested OK with branch: server-1087
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b4125f5c-1cd8-46ea-be72-bc7529122f80)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fe500afb-36d7-427c-b5e4-7828f6f4b64c)
