### ISSUE TITLE
BUG: Reference cannot be created as part of challenge update

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1126]
**Describe the bug**
Reference cannot be created as part of challenge update.

The current behavior is as follows:
If we want to create a reference i.e. on an existing challenge, we need to perform challengeUpdate mutation. The issue comes, when we intend to add additional reference to the context of the challenge. It fails, as it is required ID, which doesn't exist. So for the moment, the only possible way to create a reference is by using createReference mutations.
The issue results in inability to add references using the populator, when for example a challenge is already created.

**Comment by atstoyanov** [comment]
It's not a bug. This is how backend is designed.

For the **client-lib**:

- If the entity is new. Every reference/tagset will be new for that entity and they can be created during the entity creation in single mutation.
- If the entity exists. There are 3 situations:
   - the reference does not exist. Should be created using one  of  two mutations `createReferenceOnProfile` or `createReferenceOnContext`;
  - the reference does exist. Should be updated using the update entity mutation. `Ecoverse`, `Challenge`, `Opportunity`, `User` ...
  - the reference exists on the entity but does not exist in the incoming data (spreadsheet, client form etc.) the reference should be deleted one by one using `deleteReference` mutation.

For the **client-web** will be resolved in client-web#623

Same is valid for Tagsets.
**NB!** N/A for `Ecoverses`, becaue they have single tagset.
