### ISSUE TITLE
Spike: try out getting email verification + password reset flows working using smtp server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1140]
## Description
As a user I want to be empowered
As an admin I want the platform to be secure

## Acceptance criteria

- [ ] Test out configuring Ory to work with email verification + password reset flows. 
- [ ] …

**Comment by atstoyanov** [comment]
Results:
The verification and recovery flows have been already configured.

Changes:
- the after registration session creation should be turned off (example in #1156)
- infrastructure updates required:
  - smtp configuration should be configured using secrets. Sensitive information should not be pushed into the repository.
  - demo and dev might use the `mailslurper` to access the send e-mails.
- the web should be updated to support this routes:
   - `/auth/verify` - for email verification.  (similar to login and registration using KratosUI)
   - `/auth/recovery` - for password recovery. (similar to login and registration using KratosUI)
   - route where the user will be redirected after registration. example (`/auth/verify-email`) - this should show page to explain next step from the registration flow (email verification). example: `An e-mail was send to your email. Please check your e-mail and verify it.`
