### ISSUE TITLE
BUG:GlobalAdminChallenges credential type, fails to fulfill requirements

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1154]
**Describe the bug**
GlobalAdminChallenges credential type, fails to fulfill requirements: `GlobalAdminChallenges = 'global-admin-challenges', // able to create challenges / ecoverses / opportunities`

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2d4e4c34-13ec-46b5-bd6b-f5875af5f8fa)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5243e3f7-2fff-41c3-983d-ac799119954a)

**Comment by techsmyth** [comment]
Will remove this role, it is not used.
