### ISSUE TITLE
BUG: GraphQL Docs are not accessible on PROD

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1215]
**Describe the bug**
GraphQL Docs are not accessible on PROD.

**To Reproduce**
1. Go to https://hub.alkem.io/graphql
2. Open Docs - keep loading
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bc030d98-5432-432e-a4f8-e744c1428264)

**Expected behavior**
Prod Docs are loading successfully on server.

**Comment by techsmyth** [comment]
Leave the env as production

Find another way to show the playground docs on prod.
