### ISSUE TITLE
Update deployment workflow for test to work against Azure

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#1229]
## Description
As a QA
I want to be able to test from different branches
So that I can validate issues efficiently before they reach production.

## Acceptance criteria

- [ ] The manual dispatch workflow for test deploys to https://test.alkem.io from any branch

**Comment by Comoque1** [comment]
Deployment on test, failed: https://github.com/alkem-io/server/runs/3087608185?check_suite_focus=true
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2d13b104-50cb-4e05-97c9-0901db3c6893)

It, would be great, if we could add deployment for client-web, as part of this issue. In case another one isse required, let me know and will open.
