### ISSUE TITLE
load-sample-data doesn't work as intended

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#124]
**Describe the bug**
 CT data loading script (load-sample-data.ts) doesn't work
   - the Ecoverse singleton is referred
   - users are not properly saved (assuming it's an issue with entity relationships)
   - only the following users are created - admin, john, bob, Rutger, Rene, Alex

**To Reproduce**
1. Run CT DB Reset
2. Run CT Reset Ecoverse
3. Run CT Sample Data

**Expected behavior**
Apart from the users mentioned, valentin and angel should be added with proper email addresses and neil should be added without email address.

**Comment by techsmyth** [comment]
Just tried to reproduce this using latest on develop but could not. Can you check again?

**Comment by Comoque1** [comment]
The issues are not reproducible anymore.
