### ISSUE TITLE
BUG:  inconsistency between some field names in graphql

### ISSUE THREAD

**Issue by hero101** [alkem-io/server#1242]
**Describe the bug**
There is an inconsistency between some field names in graphql.
**CreateChallengeInput** parent field is '_parentID_'
**CreateOpportunityInput** parent field is '_challengeID_'

**Expected behavior**
**CreateChallengeInput** parent field to be renamed to '_ecoverseID_' or **CreateOpportunityInput** to have it's field renamed to '_parentID_'.

**Note: There may be more inconsistencies of the same type.**
**Note2: Also in some cases, for example, if the _challengeId_ is in the input, actually the _challengeNameId_ is needed**

**Comment by techsmyth** [comment]
good that we look at this.

the choice for parentID for creating challenge is deliberate as the parent can be an ecoverse **or** or a challenge (they are hierarchical even if we do not expose that at the moment on the client).

re nameID / UUID - if you have a particular example where you think we should change please put it in the comments. In general anytime a nameID can be used it can **always** be replaced by a UUID
