### ISSUE TITLE
BUG: When user has multiple applications to different ecoverses and one of theim deleted, none application is returned in membershipUser query

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1254]
**Describe the bug**
When user has multiple applications to different ecoverses and one of theim deleted, none application is returned in `membershipUser` query.

**To Reproduce**
1. Using 1 user create applications to multiple ecoverses
2. Delete one of the ecoverses
3. Query the user applications using `membershipUser` query, the query returns, that such ecoverse doesn't exist anymore, instead of the applications to the eixsting ecoverses.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/abe13762-53bb-4a9d-8552-0e55051b4c32)

**Expected behavior**
`MembershipUser` query returns correct results.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techsmyth** [comment]
Issue is that the user still has a credential of type EcoverseMember for the ecoverse that was deleted. 


![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2298343b-6974-4c5b-b684-1e463fd7b9f8)

The correct solution is to ensure that when a entity is deleted that any credentials with that resource ID are also removed.

**Comment by Comoque1** [comment]
The issue is not reproducible anymore.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c2ce8814-795e-49b1-a86e-6cb2e75cf018)
