### ISSUE TITLE
Mutations for managing global admin credentials

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1299]
## Description
As a developer I want a consistent approach across all credential assignments

## Acceptance criteria

- [ ] New mutations for assigning / removing global credentials: global admin, global admin community
- [ ] Move business logic related to global admin out of generic assign / revoke credentials

**Comment by Comoque1** [comment]
Mutation `removeUserAsGlobalCommunityAdmin` is not removing the user credentials.

**Comment by Comoque1** [comment]
The issue from the previous comment is addressed, hence closing the bug.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/eee1a1e2-2d12-44ac-b055-051b2be2b0a9)
