### ISSUE TITLE
Add credential for organisation-owner

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1302]
## Description
As a user I want to be able to be the responsible person for an organisation

## Acceptance criteria

- [x] new credential type: organisation-owner
- [x] New mutations to add / remove organisation owners
- [ ] Logic for deleting an organisation to manage organisation related credentials
- [x] Logic for removing an organisation-owner to ensure that there is at least one left

**Comment by Comoque1** [comment]
Seems, to work fine.
Added API tests and linked the PR to the server issue.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/785126c3-e905-4672-aa7b-85f4349360f2)
