### ISSUE TITLE
Order the list of ecoverses query

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#1307]
## Description
As a CT deployer
I want to have ecoverses displayed on the landing page ordered
So that higher value customers are higher up the ladder.

## Acceptance criteria

- [ ] Public ecoverses first
- [ ] Then combined number of challenges + opportunities

**Comment by Comoque1** [comment]
Tested OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/aa3fe940-0376-40ef-85c7-97a02c66d727)
