### ISSUE TITLE
BUG:  Activity type "id" field is null/not queriable

### ISSUE THREAD

**Issue by hero101** [alkem-io/server#1308]
**Describe the bug**
When quering the *id* field of Activity type, an error is returned

**Expected behavior**
It's expected the field to be queriable or removed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/a8fbd2e7-eb27-4e4a-94c8-9f7d9d975458)If applicable, add screenshots to help explain your problem.

Note: see how this change impacts the questions

**Comment by Comoque1** [comment]
Tested on Test env. - looks OK
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/75426eaf-32a1-41a5-a3d2-7254886fae9f)

Closing the the issue.
