### ISSUE TITLE
BUG: Registered users not able to create relations 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1319]
**Describe the bug**
A registered user should be able to create relations on opportunities that they have read access to.

**To Reproduce**

1. Navigate to "https://dev.alkem.io/graphql"
2. Perform the following mutation with only registered user:
```
mutation CreateRelation($relationData: CreateRelationInput!) {
  createRelation(relationData: $relationData) {
    type
  }
}
```
```
{
  "relationData":
  {
    "parentID": "465e5ade-78b8-464d-8f0a-8218753d5acd",
    "type": "incoming",
    "description": "How do I handle scalability?",
    "actorName": "Test",
    "actorType": "Test1",
    "actorRole": "Test2"
  }
}
```
3. The mutation fails, with authorization issue: `"message": "Authorization: unable to grant 'update' privilege: create relation: op-redirect"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/70e5d309-2869-40ad-ac9b-fd8a75301b77)

**Expected behavior**
Registered user, must be able to create relation to an opportunity.

**Comment by Comoque1** [comment]
Registered user can now created relation to an opportunity.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b8396e07-b9b6-4586-85ef-2f895a33237b)

Noting a couple of observations:
 - User can create multiple relations to the same parent using graphql - is that expected @techsmyth ?
    - added [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1325)
 - new bug will be created for removal of relations from registered users
   - added [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1017)

**Comment by Comoque1** [comment]
Closing the bug and raised other 2 related to the previous comment.
