### ISSUE TITLE
Expose sentry configuration for client

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1328]
## Description
As an admin I want all my configuration managed centrally

## Acceptance criteria

- [ ] Sentry configuration for client exposed through graphql api

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/34b6f7c1-9cfe-467b-9ccc-e54109361b4d)

**Comment by Comoque1** [comment]
Sentry configuration is exposed through graphql API
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/23abb1ff-edf4-484b-aa03-bbda5bf3d3cb)
