### ISSUE TITLE
BUG: When populating datа to server with enable "communications" feature, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#1347]
**Describe the bug**
When populating datа to server with enable "communications" feature, error is thrown.

**To Reproduce**
1. Precondition: the server has "communications" feature enabled
2. Using `populator` dev branch, upload "alkemio-sdgs.ods"
3. Error is thrown, regarding `rooms/communications`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0df87bda-7189-49b7-8875-52cbd366b584)

4. In addition, when try to query messages, error is thrown
```
query {
  ecoverses {
    community {
      discussionRoom {
        id
        messages {
          id
          message
          sender
        }
      }
    }
  }
}

```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/896baf72-9a30-4039-a5c5-4d0207ed55a2)

**Expected behavior**
When "communication" feature is enabled, user can populate data, without exceptions being thrown. User can query community messages data, with no errors.

**Comment by techsmyth** [comment]
I think if you were to reset the db, and then start up the server with comms enabled this issue may not happen. 

Looking at the stack trace above it is the assign user to community that is failing, so the user is created ok.

**Comment by Comoque1** [comment]
> I think if you were to reset the db, and then start up the server with comms enabled this issue may not happen.
> 
> Looking at the stack trace above it is the assign user to community that is failing, so the user is created ok.

Will give it a try locally.
Same behavior was experienced on demo env.

**Comment by techsmyth** [comment]
think any ecoverse / challenge / opportunity that was created without comms enabled has this issue. Should be straightforward to fix, and am pretty sure on @Enderedne radar...

**Comment by techsmyth** [comment]
Can you please retest this with the server-937 branch?

**Comment by Comoque1** [comment]
The issue is reproducible on Test env.
The error is a bit different.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0ccd698c-85c9-4b01-b0a2-e8df4f90f81a)

**Comment by techsmyth** [comment]
Needs a clean home server database?

**Comment by Comoque1** [comment]
Not able to reproduce the issue on DEV env.
Closing.
