### ISSUE TITLE
Spike: Design for Notification Service

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1365]
## Description
As a  developer I want to have a full design for what we are supporting with notifications

## Acceptance criteria

- [x] HackMD file created that details out the following: a) what events trigger notifications and when b) how the email templates for the notifications are configured c) how users manage their preferences related to receiving notifications d) how  we administer the notifications service e) ...
- [x] Timebox to a day

**Comment by valentinyanakiev** [comment]
https://hackmd.io/bPXR7NhYQ_eKlGDlRo0_Zw
