### ISSUE TITLE
API support for updating of the verification status Organisation 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1366]
## Description
As an admin I wan to be able to update the verification status of organisations

## Acceptance criteria

- [x] Verification Lifecycle associated with an Organisation
- [x] Server api for sending events to the lifecycle to be restricted to global admin / global community admin 
- [x] Current "verification" field is removed (replaced)
- [x] Lifecycle reviewed with Rene
- [x] Migration updated to work with renaming of organisation to organization (will need to be redone)
- [ ] API tests added - Valentin

## Additional Context

Add API tests

**Comment by Comoque1** [comment]
The issue is tested OK on DEV env.
Tests will be added as part of [this item](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/test-suites/57).
