### ISSUE TITLE
Spike: Jolocom version dependency analysis

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1367]
## Description
As a developer I want to be able to use the jolocom sdk v1

## Acceptance criteria

- [x] Fork the jolocom sdk v1 and try to upgrade it to the point that we are able to integrate into our stack
- [x] Enough information to be able to make decisions related to essif lab programme deliverables
- [x] Timeboxed to 2 hours

## Additional Context

There are 3+ years old transitive peer dependencies between jolocom sdk v1 and its mysql adapter.

**Comment by valentinyanakiev** [comment]
Running npm install on the sdk-storage-typeorm doesn't build it, with 6 errors (current branch used in the SDK, **NOT** main,  it is a feature branch, released (used in jolocom-sdk main branch) and not merged to main in sdk-storage-typeorm. The branch is credMetaById).

> @jolocom/sdk-storage-typeorm@4.3.0-rc0 prepare
> yarn build

yarn run v1.22.5
$ tsc -p .
src/index.ts:10:47 - error TS2305: Module '"../node_modules/@jolocom/sdk/js/storage"' has no exported member 'QueryOptions'.

10 import { IStorage, EncryptedWalletAttributes, QueryOptions, CredentialQuery, InteractionTokenQuery, InteractionQuery, InteractionQueryAttrs } from '@jolocom/sdk/js/storage'
                                                 ~~~~~~~~~~~~

src/index.ts:10:61 - error TS2305: Module '"../node_modules/@jolocom/sdk/js/storage"' has no exported member 'CredentialQuery'.

10 import { IStorage, EncryptedWalletAttributes, QueryOptions, CredentialQuery, InteractionTokenQuery, InteractionQuery, InteractionQueryAttrs } from '@jolocom/sdk/js/storage'
                                                               ~~~~~~~~~~~~~~~

src/index.ts:10:78 - error TS2724: Module '"../node_modules/@jolocom/sdk/js/storage"' has no exported member 'InteractionTokenQuery'. Did you mean 'InteractionTokenAttrs'?

10 import { IStorage, EncryptedWalletAttributes, QueryOptions, CredentialQuery, InteractionTokenQuery, InteractionQuery, InteractionQueryAttrs } from '@jolocom/sdk/js/storage'
                                                                                ~~~~~~~~~~~~~~~~~~~~~

src/index.ts:10:101 - error TS2305: Module '"../node_modules/@jolocom/sdk/js/storage"' has no exported member 'InteractionQuery'.

10 import { IStorage, EncryptedWalletAttributes, QueryOptions, CredentialQuery, InteractionTokenQuery, InteractionQuery, InteractionQueryAttrs } from '@jolocom/sdk/js/storage'
                                                                                                       ~~~~~~~~~~~~~~~~

src/index.ts:10:119 - error TS2724: Module '"../node_modules/@jolocom/sdk/js/storage"' has no exported member 'InteractionQueryAttrs'. Did you mean 'InteractionTokenAttrs'?

10 import { IStorage, EncryptedWalletAttributes, QueryOptions, CredentialQuery, InteractionTokenQuery, InteractionQuery, InteractionQueryAttrs } from '@jolocom/sdk/js/storage'
                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~

src/index.ts:443:55 - error TS2339: Property 'getRequestTokenType' does not exist on type 'typeof Interaction'.

443           params[`types${i}`] = types.map(Interaction.getRequestTokenType)
                                                          ~~~~~~~~~~~~~~~~~~~


Found 6 errors.

**Comment by valentinyanakiev** [comment]
The sdk-storage-typeorm package, used in jolocom-sdk, has a peer dependency of typeorm 0.2.24. In the package itself, the package is listed as a dev dependency, so there is something very odd in the whole approach there.

**Comment by valentinyanakiev** [comment]
sdk-storage-typeorm has dependency on jolocom/sdk which has a dependency on sdk-storage-typeorm. There is a circular dependency that will be hard to unravel quickly. Also Sdk-storage-typeorm (from the aforementioned branch) has a dependency on jolocom-lib-5.1.0, whereas jolocom-sdk (@main) has a dependency on jolocom-lib 5.2.1.

**Comment by valentinyanakiev** [comment]
Overall the whole dependency graph looks a huge mess and I don't believe there will be a quick fix, especially for someone unfamiliar with the intricate details of the packages.
