### ISSUE TITLE
[Non-functional] Consistent notation of enums and alkemio.yml

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#1370]
## Description
As a developer 
I want to have consistent coding standards 

## Acceptance criteria

- [x] Some enums use camelCase, some use XXX_YYY --> fix to XXX_YYY
- [x] alkemio.yml uses camelCase + xxx_yyy --> fix to xxx_yyy

## Additional Context

Testing focus: configuration api

**Comment by valentinyanakiev** [comment]
Re-opened the issue as there was a client-side regression.

**Comment by Comoque1** [comment]
Haven't experience issues, related to this changes (after bugs were addressed) - closing the issue.
