### ISSUE TITLE
Prototype of integration with AAD + capture of implications / options

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#14]
## Description
As a partner who deploys an instance of CT, I want to be able to authenticate users of the platform using a centralised identity provider so that people can use the platform. 

The first partner deployment is Odyssey Momentum, but before that we need to have identity / authentication embedded in the Demo.Simple application. 

## Acceptance criteria

- [x] Able to authenticate to CT using a few default accounts
- [x] Able to authenticate from the web client
- [x] Capture of implications / billing for using AAD

Authorisation design for now separate

TBD - what happens when a new user is added into CT? Do they automagically get an account within the identity provider? Onboarding?

**Comment by valentinyanakiev** [comment]
Currently, there are no implications to the billing from our AAD implementation - we are not using any paid features. However, if we ramp up our authorisation in the future, we might end up paying for roles, ring-fencing, MFA, advanced auditing, or other more advanced AAD features.
