### ISSUE TITLE
Template for tagsets on an Organization

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1455]
## Description
As a developer I want the terminology to be consistent + reflected in the api

## Acceptance criteria

- [x] Organization template that specifies the tagsets to use: "Keywords", "Capabilities". 
- [ ] Migration to update organization profiles to rename the "Skills" tagset to "Capabilities"
- [ ] Client updated to pick up the template from the organization template
- [ ] Populator updated accordingly

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6a65bd23-4c08-4a53-93f0-eb9936d54df2)

Add the same for organizations and also expose on the api

**Comment by Comoque1** [comment]
Looks OK on DEV env.
