### ISSUE TITLE
BUG: Challenges/Opportunities/ecoverses are not fetched with nameID length equal to UUID length

### ISSUE THREAD

**Issue by hero101** [alkem-io/server#1466]
**Describe the bug**
Challenge/Opportunity with nameID length equal to UUID length is not found when queried.

**To Reproduce**
1. Create a challenge or opportunity with nameID length 36 (the current UUID length)
2. Query the entity by UUID_NAMEID
3. Entity is not found

**Expected behavior**
The corresponding entity must be fetched

**Comment by Comoque1** [comment]
Tested OK on DEV env.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ef2c0457-fce2-47e9-9844-07ca567f894f)
