### ISSUE TITLE
BUG: A maximum of 9 community events, including messages, are retrieved

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1468]
**Describe the bug**
I have sent 20+ updates to a single community room. On querying the api I only ever get 9 updates: 
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/72b80a1a-1615-429c-a051-8d6025dc2874)

**Expected behavior**
All messages for now are retrieved; we will need to add pagination later.

Note: is there a configuration parameter that controls the number of events being returned?

**Comment by Comoque1** [comment]
Looks OK on Dev env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c153e614-799a-4a5d-a209-899dbab80595)
