### ISSUE TITLE
Add events for new user registration, community update sent

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1488]
## Description
As a user I want a nice welcome email when I have first logged into Alkemio.
As a user I want to be able to receive community updates by email.

## Acceptance criteria

- [x] New event type for new user profile created. 
- [ ] New event type for community update created.
- [ ] New events type for the community discussion created

## Additional Context
Payloads as per Notifications repo definitions.

**Comment by Comoque1** [comment]
Notifications are sent for all except for created discussions.
Closing this one and will address discussions issue as a separate [bug](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/notifications/64)
