### ISSUE TITLE
Migrate all 0.1.8 resolvers to 0.2.0

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#149]
## Description
As a CT owner
I want to be able to make sure all 0.1.8 APIs work in 0.2.0
So that CT services can meet the functional requirements of Odyssey and other potential deployers

## Acceptance criteria

- [ ] Odyssey data loading script can be executed without errors on 0.2.0

**Comment by techsmyth** [comment]
Replaced this bucket issue with several smaller issues.
