### ISSUE TITLE
BUG: Unable to retrieve the type of a preference definition for a Preference on a Hub

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1792]
**Describe the bug**
The type for a preference on a Hub is not returnable:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1a071c96-6a05-4459-9784-577fcc84f17b)

**To Reproduce**
Execute the following query:

query hubs {
  hubs {
    preferences {
      value
      definition {
        type
      }
    }
  }
}

**Expected behavior**
The type for the Hub Definition should be returnable

**Additional context**
The issue is that Graphql cannot return a union of enums, and we have two enums that are there as types on the return type for that entity. 

A bit of a hack workaround would be to create manually a joined up Enum that has both sets of values...

**Comment by Comoque1** [comment]
Look OK on DEV env
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d4823df4-0fd3-4ecb-ae94-75915ed49fee)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/29f25309-058e-4dfe-9d7c-2a8fbf7f36df)
