### ISSUE TITLE
Establish test enviornment that is for QA only

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#205]
## Description
As a QA I want to have a clean environment that is purely for QA

## Acceptance criteria

- [x] test.cherrytwist.org that is for QA purposes
- [x] images to come from CT azure registry
- [x] manual trigger of updated images into test using latest Azure image registry

**Comment by GhostOnTheFiber** [comment]
Hey, I have the test env up on test.cherrytwist.org. I have not set up authentication on it via AAD but can if it is needed?
