### ISSUE TITLE
Create sample load tests

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#266]
## Description
As a developer of CT I want to be able to execute load tests against the server

## Acceptance criteria

- [ ] Able to load data in as per details below
- [ ] Able to execute test cases as per details below against dev env
- [ ] Storage of the data population setup as below in a MD file and with a **name** for this test data setup (we will have multiple)
- [ ] Storage of the load test scenario, also with a name, as a MD file
- [ ] Storage of the results, including observations, with from the load test execution, with <data name> <load test name> <env> <date> somewhere in the file name

## Environment setup

Dev Env:

**Entities amount:**
  - [x] Users: 2090
  - [x] Groups: 100
  - [x] Challenges: 21 
  - [x] 10 Challenges populated with 100 users, each
  - [x] 10 Groups populated with 100 users, each

**Thread (Users) number: 1** 
***Queries:***
  - [ ] Query all Users (Name and ID)
  - [ ] Query all Challenges (Name and ID)
  - [ ] Query all Groups (Name and ID)
  - [ ] Query all Groups with specific tag (Name and ID)

***Mutations:***
- [ ] Create: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-challenge) 
  - [ ] [GroupOnEcoverse](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-ecoverse) 
  - [ ] [GroupsOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-challenge) 
  - [ ] [OpportunityOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-opportunity-on-challenge) 

- [ ] Update: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-challenge) 

- [ ] Remove: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user) 
  - [ ] [UserFromGroup](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user-from-group) 

***Queries:***

```
query {
  users {
    id
    name
  }
}
```
```
query {
  challenges {
    id
    name
  }
}
```
```
query {
  groups {
    id
    name
  }
}
```
   ```
 query {
  groupsWithTag (tag: "Team"){
    id
  }
}
```

**Comment by Comoque1** [comment]
**Environment setup:**

Dev Env:

**Entities amount:**
  - Users: 3000
  - Groups: 100
  - Challenges: 20 
  - 10 Challenges populated with 100 users, each
  - 10 Groups populated with 100 users, each

**Thread (Users) number: 1** 
***Queries:***
  - [ ] Query all Users (Name and ID)
  - [ ] Query all Challenges (Name and ID)
  - [ ] Query all Groups (Name and ID)
  - [ ] Query all Groups with specific tag (Name and ID)

***Mutations:***
- [ ] Create: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-challenge) 
  - [ ] [GroupOnEcoverse](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-ecoverse) 
  - [ ] [GroupsOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-challenge) 
  - [ ] [OpportunityOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-opportunity-on-challenge) 

- [ ] Update: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-challenge) 

- [ ] Remove: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user) 
  - [ ] [UserFromGroup](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user-from-group) 



***Queries:***

```
query {
  users {
    id
    name
  }
}
```
```
query {
  challenges {
    id
    name
  }
}
```
```
query {
  groups {
    id
    name
  }
}
```
   ```
 query {
  groupsWithTag (tag: "Team"){
    id
  }
}
```

**Comment by techsmyth** [comment]
Nice write up!
Just moved your comment up to the card description, and added some additional tests I think we need to have in there.

**Comment by Comoque1** [comment]
**[Performance Test Plan - CT(Jmeter)](https://app.zenhub.com/files/289632902/e4d25c80-5e17-4d6e-b3b5-b6b683038a99/download)**
**Thread (Users) number: 1** 
***Queries:*** 
  - [x] Query all Users (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a3306ee5-c332-4e64-9abc-1a829bae9ae9)
  - [x] Query all Challenges (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b0ec8c1e-8c86-4d54-844c-7baca0774b68)
  - [x] Query all Groups (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e2e4627a-0dd7-4a6f-b7cf-7caefdeee05c)
  - [x] Query all requests above at once:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4c80487-b055-4096-875c-a7b5fcf3b0f3)

  - [x] Get All Users: {MemberOf {Groups and Challenges}}:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3cd732d9-f921-43c8-bd36-e863311b3158)


**After performing the both queries, the responses start to fail**
  - [ ] Get All Users:{ MemberOf {Groups and Challenges{Contributers}} } !!
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e0888521-b502-4088-9351-e7d374dcfab4)

**The below 1 is not performed:**
  - [ ] Get All Users {MemborOf{Groups, Challenges{Opportunities{Profiles, Projects,Contributors}}}}

**Thread (Users) number: 100** 
***Queries:***
  - [x] Query all Users (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e8aa89f8-c9ed-41b9-8c26-24ed0cd79c09)
  - [x] Query all Challenges (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5394ae12-28ff-44a8-b5be-39fb114cc2b3)
  - [x] Query all Groups (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/73e64025-6908-483b-b5c2-a1decc4e5088)
  - [x] Query all requests above at once:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/60c1f934-5a6c-4634-a11f-e6a62d90dfc5)

**Thread (Users) number: 500** 
***Queries:***
  - [x] Query all Users (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/62d05fdd-98ba-4da0-aac6-16a37ef925e8)
  - [x] Query all Challenges (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0564d846-fecd-4af6-a99b-1b9568d2d815)
  - [x] Query all Groups (Name and ID)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9d7e4c48-492c-4813-a43c-4e62d702c0d5)
  - [x] Query all requests above at once:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cfff16c1-b0d9-49dc-bc03-32538d86b46f)



**Thread (Users) number: 1** 
***Mutations:***
- [x] Create: 
  - [x] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c6a0dca7-2320-4c36-914b-90691123a786)

  - [x] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-challenge) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1ef9c194-1406-4695-ac2e-7317b54133d6)

  - [x] [GroupOnEcoverse](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-ecoverse) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7f8dfa0a-3e94-4574-8833-d308fadd1c5e)

  - [x] [GroupsOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-challenge) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b3bc2ee9-6819-4f44-a903-c4e24e64f7dd)

  - [x] [OpportunityOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-opportunity-on-challenge) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/26d02ac9-03e5-44c1-98f7-a0c5a223051b)

- [x] Update: 
  - [x] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-user) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/95b24d23-c4b4-4b83-97a5-dce76cc1d71d)

  - [x] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-challenge) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fc75d59a-339d-4668-8c23-9448b1082640)

- [x] Remove: 
  - [x] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9f8d2718-8223-483e-bddf-79e41c28b150)

  - [x] [UserFromGroup](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user-from-group) 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ef33fa39-931d-4c6a-b460-e3c8994281ca)

**Comment by Comoque1** [comment]
**Results of Load testing:**

**Thread (Users) number: 1** 
***Queries:***
  - [ ] Query all Users (Name and ID)


  - [ ] Query all Challenges (Name and ID)
  - [ ] Query all Groups (Name and ID)
  - [ ] Query all Groups with specific tag (Name and ID)

***Mutations:***
- [ ] Create: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-challenge) 
  - [ ] [GroupOnEcoverse](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-ecoverse) 
  - [ ] [GroupsOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-group-on-challenge) 
  - [ ] [OpportunityOnChallange](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-opportunity-on-challenge) 

- [ ] Update: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-user) 
  - [ ] [Challenge](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-challenge) 

- [ ] Remove: 
  - [ ] [User](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user) 
  - [ ] [UserFromGroup](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/remove-user-from-group)

**Comment by Comoque1** [comment]
**[Performance Test Plan - CT(Jmeter)](https://app.zenhub.com/files/289632902/e4d25c80-5e17-4d6e-b3b5-b6b683038a99/download)**
**Thread (Users) number: 1** 
***Queries:*** 

  - [x] Query all requests above at once:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4c80487-b055-4096-875c-a7b5fcf3b0f3)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/06fbe76e-db24-479e-98a0-c24cb5e8f6e3)


  - [x] Get All Users: {MemberOf {Groups and Challenges}}:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3cd732d9-f921-43c8-bd36-e863311b3158)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a281d2b4-7206-4358-a98c-2394e64a212c)

**After performing the both queries, the responses start to fail** - **invalid query**
  - [ ] Get All Users:{ MemberOf {Groups and Challenges{Contributers}} } !!
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e0888521-b502-4088-9351-e7d374dcfab4)

**The below 1 is not performed:**
  - [x] Get All Users {MemborOf{Groups, Challenges{Opportunities{Profiles, Projects}}}}
    - **After - removed contributors**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d71f70ca-2280-4e04-9dec-bff4a147c775)

**Thread (Users) number: 100** 
***Queries:***

  - [x] Query all requests above at once:
     - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/60c1f934-5a6c-4634-a11f-e6a62d90dfc5)
     - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/44d44313-3ca0-4a71-a527-77c1f3bbefe8)

**Thread (Users) number: 500** 
***Queries:***

  - [x] Query all requests above at once:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cfff16c1-b0d9-49dc-bc03-32538d86b46f)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e24e3266-a0cf-4bd3-b2e7-ab28764d5c6c)
