### ISSUE TITLE
Provide the current Innovation Hub via api

### ISSUE THREAD

**Issue by me-andre** [alkem-io/server#2829]
For Innovation Hubs to work reliably, we need to be able to unambiguously detect an innovation hub (using subdomain etc).

## Acceptance criteria
- [ ] extend the platform.innovationHub field so that it returns the current detected InnovationHub if no parameters are supplied

**Comment by techsmyth** [comment]
@me-andre yes the innovation hub detection should be done by the serve i.e. it should be possible for any client to basically say "what is my innovation hub"
