### ISSUE TITLE
Updated User is not displayed as part of "Users" query

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#286]
**Describe the bug**
When a User is `created` and `updated` afterward, it is not added in the results for "Users" query

**To Reproduce**
1. Go to [env](http://localhost:4000/graphql)
2. Create a "User", using [this mutation](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user)
3. List all "Users" - the created User i**s available** in the results
3. Update the "User", using [this mutation](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/update/update-user)
4. List all "Users" - the updated "User" is **not available** in the results

**Expected behavior**
When a user is updated, it must be visible, when searched with "Users" query

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser:Chromium
    - Version: 86.0.4240.111 

**Additional context**
If the "User" is searched by ID, results are available

**Comment by techsmyth** [comment]
Tried to reproduce this error using steps above but could not - update is working ok for me.

**Comment by Comoque1** [comment]
Looks li it is not reproducible anymore. We can close/remove the bug.
