### ISSUE TITLE
Optimise the speed of the addUserToGroup mutation

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#298]
## Description
As a populator of CT, I want the addition of a user to group to be super fast

## Acceptance criteria

- [ ] remove eager loading of user by groups
- [ ] update the mutation addUserToGroup to reflect eager loading not used
- [ ] update other usages of UserGroup

**Comment by valentinyanakiev** [comment]
remove eager loading of user to groups -> currently it's lazy loading

**Comment by techsmyth** [comment]
fixed the description: remove the eager loading by groups of users
