### ISSUE TITLE
Attempting to create the same user twice doesn't return error through the api

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#314]
**Describe the bug**
Message is missing in the response, when an attempt for creating the same user twice is done. There is such message in the Server service log.

**To Reproduce**
1. Go to [env](http://localhost:4000/graphql)
2. Create the same user twice - it is not created, but there is no such message in the response

**Expected behavior**
Message should be added in the response (i.e. User "x" has already been added) or just a boolean flag (true/false)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/43a64f1d-c7b4-4916-bac0-7424902557ce)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser:Chromium
    - Version: 86.0.4240.111 

**Additional context**
After a discussion with @techsmyth we agreed, this to be addressed after Momentum event

**Comment by techsmyth** [comment]
Fixed this with the PR earlier on separating user profile + account creation

**Comment by Comoque1** [comment]
**Tested: OK**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9715effa-25f0-4152-b2fa-be16475239dc)
