### ISSUE TITLE
CreateUser on Dev is throwing error 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#341]
**Describe the bug**
CreateUser on Dev is throwing error, but the User is created

**To Reproduce**
1. Go to [URL](https://dev.cherrytwist.org/graphql/)
2. Use the [query ](https://github.com/cherrytwist/Server/blob/develop/graphql-samples/mutations/create/create-user)to Create a User
    - Note: VALID Token must be provided in the headers
4. Error is thrown ( `"message": "CompactToken parsing failed with error code: 80049217"`) when the query is performed, **but the user is created**

**Expected behavior**
User must be created successfully.
None error must be thrown.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4efaf258-31bf-4618-a2bf-16ce664afacb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser:Chromium
    - Version: 86.0.4240.111

**Comment by techsmyth** [comment]
Reproduced and got the same error on dev. With a local dev setup the same query works. Also creating a user via the admin page on the web client works - something to do with how requests are being sent in via GraphQL interface?

Will need Valentin to debug this I think - after have updated the env vars.

mutation CreateUser($userData: UserInput!) {
  createUser(userData: $userData) {
    name
    id
    lastName
    firstName
    city
    country
    gender
    
  }
}

{"userData":
  {
    "name": "Valentin5",
    "firstName": "Valentin5",
    "lastName": "Valentin4",
    "email": "asdf546444@asdf.ml",
    "aadPassword": "lajsdjflk908324#2F"
  }
}

**Comment by Comoque1** [comment]
Doesn't seem to be related only to graphql interface:

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e2cb0703-cc8a-476e-98c5-f8906c44db36)

**Comment by Comoque1** [comment]
Tested OK
