### ISSUE TITLE
BUG: When connection is lost on RT whiteboard, users view become un-synced

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#3498]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/building-alkemio-org/challenges/testingexperiment-3692/collaboration/1221trew-6194
2. Using one user open the WB RT and edit things
3. On another browser open the same WB RT and edit things - both users see the changes
4. The second user stops the browser internet connection - dialog for no session shows up
5. Start the connection and close the "No session dialog"
6. Start typing with both users - they don't see each other changes, which results in data loss after saving

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
@valentinyanakiev good to put a size on this one...
