### ISSUE TITLE
HTTP Request Logging on CT Server

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#355]
## Description
As a CT DevOps consultant
I want to be able to log HTTP requests to the server
So that I can analyze the performance of the API

## Acceptance criteria

- [ ] All GraphQL queries are logged on the server
- [ ] There is a separate Winston log category for the GraphQL requests

**Comment by techsmyth** [comment]
With the new LOGGING_PROFILING_ENABLED variable profiling can now be enabled. Note: the log level also needs to be at verbose for this to be shown.
