### ISSUE TITLE
BUG: User edit error

### ISSUE THREAD

**Issue by OlegSubik** [alkem-io/server#377]
**Describe the bug**
Client receives the error after sending a request to edit user data.
ER_NO_DEFAULT_FOR_FIELD: Field 'description' doesn't have a default value

**Screenshots**
Error:
![image.png](https://images.zenhubusercontent.com/5f9c20ca91c6228710eb978a/80da37e2-53d0-4588-8c18-cd04a24abeb1)
Req body:
![image.png](https://images.zenhubusercontent.com/5f9c20ca91c6228710eb978a/f8fb5a5b-68a3-4775-9b89-2fa3185f5814)

**Comment by techsmyth** [comment]
Just tried to reproduce this but could not locally when going against a server instance - it may be in the graphql client in the web.client.

Which environment are you running against?
Can you share the template mutation?

mutation UpdateUser($userID: Float!, $userData: UserInput!) {
  updateUser(userID: $userID, userData: $userData) {
    name,
  	email,
    profile {
      description
    }
    
  }
}

{
  "userID": 4,
  "userData":
  {
    "name": "Valentin",
    "city": "Sofia",
    "profileData": {
      "description": "something",
      "tagsetsData": {
        "name": "test",
        "tags": ["er", "is"]
      }
    }
  }
}

**Comment by techsmyth** [comment]
Ok, was able to reproduce with the following variable:
{
  "userID": 7,
  "userData":
  {
    "name": "Valentin",
    "city": "Sofia",
    "profileData": {
      "description": "something",
      "tagsetsData": [
        {"name": "test",
        "tags": ["er", "is"]
        }
      ],
      "referencesData": [
        {
          "name": "tests",
        	"uri":"tests"
        }
      ]
    }
  }
}
