### ISSUE TITLE
Analysis of server query performance

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#389]
## Description
As a deployer of CT, I want to have queries that return quickly

## Acceptance criteria

- [x] Analysis of what fields are eager loaded and that could lead to performance issues
- [x] Analysis of key field queries to see where the time is going

**Comment by valentinyanakiev** [comment]
https://miro.com/app/board/o9J_kgbl2PY=/

**Comment by valentinyanakiev** [comment]
Key queries that load the longest list of dependencies are the challenge queries.
