### ISSUE TITLE
Remove eager loading of opportunities by a challenge

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#397]
## Description
As a CT user I want the system to be performant and only load the data that is needed

## Acceptance criteria

- [ ] Opportunities no longer use eager loading

**Comment by Comoque1** [comment]
**[Performance Test Plan - CT(Jmeter)](https://app.zenhub.com/files/289632902/e4d25c80-5e17-4d6e-b3b5-b6b683038a99/download)**
**Thread (Users) number: 1** 
***Queries:*** 

  - [x] Query all requests above at once:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4c80487-b055-4096-875c-a7b5fcf3b0f3)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/06fbe76e-db24-479e-98a0-c24cb5e8f6e3)
    - **results 20201106**
![image](https://user-images.githubusercontent.com/23620658/98306588-cd1dbe00-1fcc-11eb-870c-f0b6e4cb2fd9.png)


  - [x] Get All Users: {MemberOf {Groups and Challenges}}:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3cd732d9-f921-43c8-bd36-e863311b3158)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a281d2b4-7206-4358-a98c-2394e64a212c)
    - **results 20201106**
![image](https://user-images.githubusercontent.com/23620658/98308022-cb092e80-1fcf-11eb-8639-0e2feeb05748.png)


  - [x] Get All Users {MemborOf{Groups, Challenges{Opportunities{Profiles, Projects}}}}
    - **After - removed contributors**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d71f70ca-2280-4e04-9dec-bff4a147c775)
    - **results 20201106**
![image](https://user-images.githubusercontent.com/23620658/98308360-8205aa00-1fd0-11eb-9a8b-aa2504f5be28.png)



**Thread (Users) number: 100** 
***Queries:***

  - [x] Query all requests above at once:
     - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/60c1f934-5a6c-4634-a11f-e6a62d90dfc5)
     - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/44d44313-3ca0-4a71-a527-77c1f3bbefe8)
    - **results 20201106**
![image](https://user-images.githubusercontent.com/23620658/98306795-37366300-1fcd-11eb-93b4-9a7a05244023.png)


**Thread (Users) number: 500** 
***Queries:***

  - [x] Query all requests above at once:
    - **before**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cfff16c1-b0d9-49dc-bc03-32538d86b46f)
    - **after**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e24e3266-a0cf-4bd3-b2e7-ab28764d5c6c)
    - **results 20201106**
![image](https://user-images.githubusercontent.com/23620658/98307255-0b67ad00-1fce-11eb-9475-8ade397b8cea.png)
