### ISSUE TITLE
Make it easy to get started with the Server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#41]
## Description
As a contributor I want that it is very easy to get a running server going so that I can quickly test it out.

## Acceptance criteria
- [x] add default configuration
- [x] update docker compose files to use the variable from the .env file
- [x] update documentation to describe known problems that may be encountered
- [x] update documentation to have two target use cases (a) getting the server quickly running based on docker-compose (b) doing development based on "npm start" & then using a mysql container for the db potentially

**Comment by atstoyanov** [comment]
The `.env` file contains sensitive security information and should not be committed. Once committed the git will track it even if it is ignored in the .gitignore file which will lead to inevitable commit.

Once the `.env` file is created in the root folder docker compose will use it.
> By default, the docker-compose command will look for a file named .env in the directory you run the command.

https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

**Comment by techsmyth** [comment]
It is simply a default password - and only running locally. I would really like to involve any file creation / editing on the first impression loop.

Maybe we have also a "production" build that strips this file out?

**Comment by techsmyth** [comment]
Also for the running of the docker-compose - there was a lot of text coming by on the command line, possible to supress?

**Comment by atstoyanov** [comment]
I hope contributors won't be easily scared by console output from docker. :)

**Comment by techsmyth** [comment]
As long as it is only a few lines of code - it feels messy when screens of warnings fly by and is hard to see what is actually relevant.
