### ISSUE TITLE
Increase maximum number of simultaneous connections to Server and DB

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/server#410]
## Description
As a CT deployer
I want to have >200 users connect simultaneously
So that my Ecoverse can support 2000 users.

## Acceptance criteria

- [ ] CT connections drops don't happen during performance tests.

## Additional Context

MySQL by default supports 100 connections.

**Comment by Comoque1** [comment]
Note the setup and number of requests after which, the requests start failing:

**Setup 1:**
 - Environment - [Test](https://test.cherrytwist.org/graphql)
 - Number of users: **2100**
 - Number of challenges: **21**
 - Number of Groups (Ecoverse and Challenge groups): **100**
 - All Users are assigned to challenges

Up to total 192 requests (get all users), all are passing
Up to total 195 requests (get all users), ~ 1.04% of requests are starting failing

**Setup 2:**
 - Environment - [Dev](https://dev.cherrytwist.org/graphql)
 - Number of users: **36**
 - Number of challenges: **9**
 - Number of Groups (Ecoverse and Challenge groups): **120**
 - All Users are assigned to challenges

Up to total 650 requests (get all users), all are passing
Up to total 657 requests (get all users),~2.74% of requests are starting failing

**Query:**
```
query {
  users {
    name
    id
    email
  }
}
```
