### ISSUE TITLE
Bug: able to remove users from Ecoverse.members group

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/server#412]
## Description
It should not be possible to remove users directly from the Ecoverse.members group.

Current `users` query returns all Ecoverse.members. But if you remove an user from the ecoverse.members group you can't add them back.

## Acceptance criteria

- [ ] Error thrown if try to remove a user directly from the members group on the ecoverse

**Comment by techsmyth** [comment]
There should be additional business logic around the ecoverse members group - there is for addition but not for removal.
