### ISSUE TITLE
BUG: Documentation - Logging

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/server#416]
**Describe the bug**
Verbose is not acceptable value for:
AUTH_AAD_LOGGING_LEVEL=Error|Warning|Info|Verbose.

**To Reproduce**
1. set `AUTH_AAD_LOGGING_LEVEL=Verbose`
2. Start the project

**Expected behavior**
The documentation to describe correctly the accepted values.

**Screenshots**
![image](https://user-images.githubusercontent.com/3524687/98372371-50c7c100-2046-11eb-98a9-b2629dc3af20.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techsmyth** [comment]
Just looked online:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d9dc3203-0605-4e54-af5a-94dcf05e8c55)

From https://github.com/AzureAD/passport-azure-ad
