### ISSUE TITLE
Image management for users, groups & challenges 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#44]
## Description
As a user I want to be able to store images with the users, groups and challenges so that I can manage that visual information together with the relevant text. 

Key support needed:
- avatars for users
- logos for groups, challenges

Size guidelines / restrictions?
How would this data would be migrated / pulled from another environment?
Where is the data stored?

## Acceptance criteria

- [ ] Able to store and retrieve an avatar with the user
- [ ] Able to store + retrieve the logo for a group and a challenge

## Additional Context

Sample export from Odyssey below. 
{"id":1258044,"name":"John Doh","email":"neil@thesmyths.eu","first_name":"John","last_name":"Doh","avatar":{"url":"https://d3evbfoo20rmgo.cloudfront.net/uploads/user_organization/avatar/1258044/556974af-77ef-4263-877b-e9ae565d38d8.jpg","thumb":{"url":"https://d3evbfoo20rmgo.cloudfront.net/uploads/user_organization/avatar/1258044/thumb_556974af-77ef-4263-877b-e9ae565d38d8.jpg"},"small_thumb":{"url":"https://d3evbfoo20rmgo.cloudfront.net/uploads/user_organization/avatar/1258044/small_thumb_556974af-77ef-4263-877b-e9ae565d38d8.jpg"},"mini_thumb":{"url":"https://d3evbfoo20rmgo.cloudfront.net/uploads/user_organization/avatar/1258044/mini_thumb_556974af-77ef-4263-877b-e9ae565d38d8.jpg"}},"groups":[{"is_admin":false,"id":29565,"name":"Global Odyssey Community","status":"accepted","last_invited_in":null},{"is_admin":false,"id":29579,"name":"Track 'Nature 2.0'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":29580,"name":"Track 2019 'Scaling Ecosystems'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":29584,"name":"Track 2019 'Digital Nation’s Infrastructure'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":29589,"name":"Track 'Fossil Free Future'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":29629,"name":"Track 2019 '21st Century Digital Citizenship'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":31139,"name":"Jedi 2019","status":"accepted","last_invited_in":null},{"is_admin":false,"id":31830,"name":"Odyssey Hackathon 2019","status":"accepted","last_invited_in":null},{"is_admin":false,"id":35978,"name":"Track 'Conscious Cities'","status":"accepted","last_invited_in":null},{"is_admin":false,"id":39369,"name":"PrivateTracer","status":"accepted","last_invited_in":1585912554171}],"fields":{},"is_registered":true,"created_at":1545337073581,"updated_at":1598534611216}

**Comment by atstoyanov** [comment]
Just a reminder
https://www.apollographql.com/blog/file-uploads-with-apollo-server-2-0-5db2f3f60675/
