### ISSUE TITLE
BUG: Opportunities should not be restricted resource

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/server#446]
**Describe the bug**
Opportunities should not be restricted resource

**To Reproduce**
1. Execute: 
```graph
  challenges {
    name
    opportunities {
      name
      textID
      aspects {
        title
        framing
        explanation
      }
      actorGroups {
        name
        description
        actors {
          name
          value
          description
          impact
        }
      }
    }
  }
}
```
without authentication header

**Expected behavior**
Returns data without "UNAUTHORIZED" error.

**Comment by atstoyanov** [comment]
@techsmyth 
Which fields should be public? Because currently none of them are!

**Comment by techsmyth** [comment]
Yes this is an issue, will fix once my two open PRs on the same area of the code are merged
