### ISSUE TITLE
Defined set of errors + codes on the server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#539]
## Description
As a CT deployer
I want to get consistent error feedback across the stack
So that I can operate CT efficiently.

## Acceptance criteria

- [x] AuthenticationError: when a user can't authenticate
- [x] ForbiddenError: when a user is not authorised to access a particular api
- [x] UserInputError specific error type consistently on the api

## Additional Context

https://www.apollographql.com/docs/apollo-server/data/errors/
https://miro.com/app/board/o9J_lduESCU=/

**Comment by atstoyanov** [comment]
Currently we have DB Errors leaking through the graphql. We need
server-side input validation. the server relies on the graphql type validation but that is not enough. Text fields length is not validated until it hits the DB.
