### ISSUE TITLE
Mutation: addUserToOpportunity

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#547]
## Description
As a developer I want a clear api call for adding a user to an opportunity

## Acceptance criteria

- [ ] Mutation: addUserToOpportunity, on the challenge service
- [ ] Mutation to only take place if the user is a member of the challenge

**Comment by Comoque1** [comment]
Tested on Dev:
- [x] Mutation: addUserToOpportunity, on the challenge service - **OK**
- [x] Mutation to only take place if the user is a member of the challenge - **OK**
