### ISSUE TITLE
Groups to disply the context they are from 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#553]
## Description
As a user I want to know when I carry out a search where group results are from 

## Acceptance criteria

- [ ] Search result for groups, or groups in general, to be able to have the context (i.e. container) for the group

**Comment by Comoque1** [comment]
Searching for groups  by a term, returns groups parent type 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6679eefd-6eda-4d8c-9cd1-1b858cb9b650)

Having only the parent type (i.e. challenge, ecoverse, opportunity,..), doesn't clear to which challenge the group is related. the parent details (i.e. **name**), could bring additional value.

**Comment by Comoque1** [comment]
Tested OK on Dev

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0511b8d8-d897-420c-9caf-616f79473012)
