### ISSUE TITLE
BUG: Anonymous user can see projects under opportunity

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#578]
**Describe the bug**
Anonymous user can see projects under opportunity.

**To Reproduce**
1. Go to [dev env](https://dev.cherrytwist.org/graphql)
2. Do not use authorization token
2. Set the following query:
```
query {
  opportunity(ID: 1) {
    projects {
      id
      name
      aspects {
        id
      }
    }
  }
}
```

3. User sees the project details:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/90cf7db2-c0cd-44f0-9991-9cd92d068909)

**Expected behavior**
Anonymous user, must be forbidden to see project, no matter querying them directly or through opportunity

**Comment by techsmyth** [comment]
Not a bug, at the moment projects are visible to anonymous users
