### ISSUE TITLE
Migration for existing production CT servers: keeping IDs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#590]
## Description
As an existing deployer of CT I want to be able to bring my db to a point where it can tie into migrations

## Acceptance criteria

- [ ] Process and supporting tooling to bring an existing db over to support migrations
- [ ] Existing identifiers for entities, especially users, should *not* be changed

## Additional Context
The identifiers have to remain the same for Odyssey as they depend on those IDs to do backwards population from their local cache (grrrr)

**Comment by valentinyanakiev** [comment]
This is the script to bring Odyssey DB to date with the init migration:

CREATE TABLE `migrations_typeorm` (
  `id` int NOT NULL AUTO_INCREMENT,
  `timestamp` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

insert into cherrytwist.migrations_typeorm (timestamp, name)
values ("1606214000200", "init1606214000200");
