### ISSUE TITLE
Expand the clientConfig to also provide UI meta data

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#601]
## Description
As a deployer of CT, I want the UI to display options relevant for my ecoverse 

## Acceptance criteria

- [ ] server: clientConfig query to hold both AAD config and meta-data on how to configure the UI 

Note: this is a breaking change for the client, so client needs to be updated at the same time as the server.

## Additional Context
Sample such file below:
{
  "name": "default-ux-template",
  "description": "sample ecoverse template based on Odyssey ecoverse setup; used by CT Web Client to configure the display / options to end users",
  "users": [
    {
      "name": "default",
      "tagsets": ["skills", "keywords"]
    }
  ],
  "opportunities": [
    {
      "name": "default",
      "actor-groups": ["keyUsers", "stakeholders"],
      "aspects": ["prototype", "economic-win", "board_member_feedback", "building_blocks", "legal_aspects", "opensource_license", "identity_role", "cso","international_standards"],
      "relations": ["members", "groups"]
    }
  ]
}

**Comment by valentinyanakiev** [comment]
Are we sure that users and opportunities have multiple values in the template? Why do we need that for UX template?
