### ISSUE TITLE
BUG: users query not returning profile data (was: After performing  "updateProfile" mutation, with Ecoverse admin user, the response is positive but the actual update is not successful

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#646]
**Describe the bug**
After performing  "updateProfile" mutation, with Ecoverse admin user, the response is positive but the actual update is not successful

**To Reproduce**
1. Navigate to [dev env](https://dev.cherrytwist.org/graphql)
2. Authenticate with ecoverse.admin@devcherrytwist.onmicrosoft.com
3. Perform the following mutation:
```
mutation updateProfile($profileData: ProfileInput!, $ID: Float!) {
    updateProfile(profileData: $profileData, ID: $ID)
  }
```
```
{
    "ID": 5,
    "profileData": {
      "description": "some ccc",
      "avatar": "http://cccc"
    }
  }
```
4. The response is true: 
```
{
  "data": {
    "updateProfile": true
  }
}
```
5. Query the user profile to verify the update
```
query {
  user(ID: "5") {
    profile {
      avatar
      description
    }
  }
}
```
6. The user profile remains unchanged:
```
{
  "data": {
    "user": {
      "profile": {
        "avatar": "https://eu.ui-avatars.com/api/?name=Evgeni+Dimitrov&background=0D8ABC&color=fff",
        "description": "ssdfsda"
      }
    }
  }
}
```

**Expected behavior**
When updating user profile with ecoverse admin user, it must be reflected.

**Comment by techsmyth** [comment]
Issue is not with the profile updating but the members query - it is never returning profile data, so those strings are always null. 

to add a test?

**Comment by Comoque1** [comment]
Test added with [this branch](https://github.com/cherrytwist/Server/commit/643e189c87a227b20ddc88765034ac4211e9fa7c).
The query seems to work, but the entities aren't updated.
