### ISSUE TITLE
BUG: several unused packages included in deployment

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#695]
**Describe the bug**
Using a tool called depcheck on the server:

Unused dependencies
* @nestjs/platform-express
* cd
* elastic-apm-node
* graphql-tools
* msal
* mysql
* node-fetch
Unused devDependencies
* @microsoft/microsoft-graph-types
* @nestjs/schematics
* @types/jest
* @types/node-fetch
* @types/passport-local
* eslint-plugin-import
* ts-loader
* tsconfig-paths

not sure all are valid but likely at least a few of the dependencies can be removed...

**Comment by valentinyanakiev** [comment]
Not removing dev dependencies -> types are being used. Leaving @nestjs, mysql (the server can't start without mysql package...) and graphql-tools. Rest of the packages will be removed.
