### ISSUE TITLE
BUG: Removing entity which has sub-entities, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#712]
**Describe the bug**
When there is an Opportunity with sub-entity project, the opportunity cannot be removed and error is thrown.

**To Reproduce**
1. Navigate to: https://dev.cherrytwist.org/graphql
2. Create the following entities:
 - Challenge > Opportunity > Project
3. Delete the Opportunity
Error is thrown:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b41bcd24-6622-4726-a8c9-c63eb7ef932a)

**Expected behavior**
When removing an entity, all sub-entities must be removed

**Comment by techsmyth** [comment]
Note that there is another flag on TypeORM as per usage on Application entity:
    { eager: false, cascade: true, onDelete: 'CASCADE' }
