### ISSUE TITLE
BUG: Unauthorized users have privileges to perform mutations

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#720]
**Describe the bug**
Unauthorized users have privileges to perform mutations.

**To Reproduce**
1. Run the "auth" `tests npm run-script test:it ./test/non-functional/auth/` for:
 - **community admin - 19 failing**
   - removeActor
   - removeActorGroup
   - removeAspect
   - removeChallenge
   - updateActor
   - updateAspect
   - updateOpportunity
   - updateChallenge
   - createAspectOnProject
   - createRelation
   - createAspect
   - createActor
   - createActorGroup
   - createProject
   - createGroupOnOpportunity
   - createOpportunityOnChallenge
   - createGroupOnChallenge
   - createChallenge
   - createGroupOnEcoverse

- **ecoverse member- 34 failing**
   - removeUser
   - removeActor
   - removeActorGroup
   - removeAspect
   - removeChallenge
   - removeUserFromGroup
   - removeGroupFocalPoint
   - assignGroupFocalPoint
   - addChallengeLead
   - addUserToOpportunity
   - addUserToGroup
   - addUserToChallenge
   - addTagToTagset
   - replaceTagsOnTagset
   - updateUser
   - updateOrganisation
   - updateActor
   - updateAspect
   - updateOpportunity
   - updateChallenge
   - createAspectOnProject
   - createRelation
   - createAspect
   - createActor
   - createActorGroup
   - createProject
   - createGroupOnOpportunity
   - createOpportunityOnChallenge
   - createGroupOnChallenge
   - createGroupOnEcoverse
   - createChallenge
   - createGroupOnEcoverse
   - createTagsetOnProfile
   - createReferenceOnContext
   - createReferenceOnProfile
   - createOrganisation
  
- **anonymous user- 81 failing**

**Expected behavior**
All authorization tests must pass.

**Comment by valentinyanakiev** [comment]
PASS  test/functional/integration/opportunity/opportunity.it-spec.ts (73.244 s)
 PASS  test/non-functional/auth/community-admin-user.it-spec.ts (64.646 s)
 PASS  test/non-functional/auth/ecoverse-member-user.it-spec.ts (64.449 s)
 PASS  test/non-functional/auth/anonymous-user.it-spec.ts (58.113 s)
 PASS  test/non-functional/auth/ecoverse-admin-user.it-spec.ts (66.499 s)
 PASS  test/non-functional/auth/global-admin-user.it-spec.ts (70.22 s)
 PASS  test/functional/integration/challenge/query-challenge-data.it-spec.ts (64.67 s)
 PASS  test/functional/e2e/user-management/create-user.e2e-spec.ts (67.967 s)
 PASS  test/functional/e2e/user-management/user-to-group.e2e-spec.ts (74.824 s)
 PASS  test/functional/integration/relations/relations.it-spec.ts (57.881 s)
 PASS  test/functional/integration/context/context.it-spec.ts (57.734 s)
 PASS  test/functional/integration/aspect/aspect-on-project.it-spec.ts (59.617 s)
 PASS  test/functional/integration/challenge/flows-challenge.it-spec.ts (58.888 s)
 PASS  test/functional/e2e/user-management/update-user.e2e-spec.ts (69.8 s)
 PASS  test/functional/integration/aspect/aspect-on-opportunity.it-spec.ts (59.321 s)
 PASS  test/functional/integration/actor/actor.it-spec.ts (58.986 s)
 PASS  test/functional/integration/challenge/other-entities-to-challenge.it-spec.ts (57.769 s)
 PASS  test/functional/integration/challenge/create-challenge.it-spec.ts (62.692 s)
 PASS  test/functional/integration/actor-groups/actor-groups.it-spec.ts (59.926 s)
 PASS  test/functional/e2e/user-management/remove-user.e2e-spec.ts (69.374 s)
 PASS  test/functional/e2e/user-management/user.e2e-spec.ts (58.553 s)
 PASS  src/domain/user/user.service.spec.ts
 PASS  src/domain/actor-group/actor-group.resolver.spec.ts
 PASS  src/utils/metadata/metadata.resolver.spec.ts
 PASS  src/app.controller.spec.ts
 PASS  src/domain/organisation/organisation.resolver.spec.ts
 PASS  src/domain/challenge/challenge.resolver.mutations.spec.ts
 PASS  src/utils/data-management/data-management.controller.spec.ts
 PASS  src/utils/data-management/data-management.service.spec.ts
 PASS  src/domain/opportunity/opportunity.resolver.spec.ts
 PASS  src/domain/organisation/organisation.service.spec.ts
 PASS  src/domain/opportunity/opportunity.service.spec.ts
 PASS  src/domain/user-group/user-group.resolver.spec.ts
 PASS  src/domain/reference/reference.resolver.spec.ts
 PASS  src/utils/config/config.service.spec.ts
 PASS  src/domain/relation/relation.resolver.spec.ts
 PASS  src/domain/user-group/user-group.service.spec.ts
 PASS  src/utils/bootstrap/bootstrap.service.spec.ts
 PASS  src/domain/challenge/challenge.service.spec.ts
 PASS  src/domain/profile/profile.resolver.spec.ts
 PASS  src/domain/project/project.resolver.spec.ts
 PASS  src/domain/context/context.resolver.spec.ts
 PASS  src/domain/ecoverse/ecoverse.service.spec.ts
 PASS  src/utils/search/search.resolver.spec.ts
 PASS  src/utils/config/config.resolver.spec.ts
 PASS  src/domain/tagset/tagset.resolver.spec.ts
 PASS  src/domain/aspect/aspect.resolver.spec.ts
 PASS  src/utils/ms-graph/ms-graph.service.spec.ts
 PASS  src/domain/actor/actor.resolver.spec.ts (5.126 s)
 PASS  src/domain/user/user.resolver.spec.ts
 PASS  src/domain/agreement/agreement.resolver.spec.ts
 PASS  src/utils/metadata/metadata.service.spec.ts
 PASS  src/domain/did/did.resolver.spec.ts
