### ISSUE TITLE
Update graphql client authentication configuration api

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#783]
## Description
As a admin I want to be able to configure the platform to use the simple auth provider

## Acceptance criteria

- [x] Remove root level query "client Config" (no longer used)
- [x] Expand Config type to have schema as below

## Additional Context

configuration {
  template {

  }
  authenticationProviders {
    aad {}
    simpleAuth {
          issuer: url
          tokenEndpoint: url
    } 
  }
}

https://swagger.io/docs/specification/authentication/openid-connect-discovery/

**Comment by valentinyanakiev** [comment]
Changing the original api in AC to:

{
  "authenticationProviders": [
    {
      "name": "Simple",
      "label": "Log in",
      "icon": "",
      "enabled": true,
      "config": {
        // simple authentication specific configuration
      }
    },
    {
      "name": "Microsoft",
      "icon": "",
      "label": "Log in with Microsft",
      "enabled": true,
      "config": {
        // microsoft specific configuration
      }
    },
    {
      "name": "Google",
      "icon": "",
      "label": "Log in with Google",
      "enabled": false,
      "config": {
        // google specific configuration
      }
    }
  ]
}
