### ISSUE TITLE
BUG: Removing user profile fields (e.g. phone number) is not preserved

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#790]
**Describe the bug**
Updated user data is not preserved

**To Reproduce**
1. Go to [dev env](https://dev.cherrytwist.org/graphql)
2. Set the following mutation to change user details:
```
mutation UpdateUser($userID: Float!, $userData: UserInput!) {
  updateUser(userID: $userID, userData: $userData) {
    name,
  	email,
    phone
  }
}
```
```
{"userID": 3,
  "userData":
  {
    "phone": ""

  }
}
```

3. Result:
```
{
  "data": {
    "updateUser": {
      "name": "admin cherrytwist",
      "email": "admin@cherrytwist.org",
      "phone": "+35966666666"
    }
  }
}
```
Removing phone number is not preserved.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/eaf57ebc-c2af-4899-a1b5-c6ca141cb85d)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/43591674-471a-4481-8e9f-c2736ac1212e)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5e3b04db-7ee4-4f35-8696-c0084e559e6c)

**Expected behavior**
When updating user profile, changes must be preserved.

**Comment by techsmyth** [comment]
No longer reproducible
