### ISSUE TITLE
BUG: Host is not returning groups

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#824]
**Describe the bug**

**To Reproduce**
1. Use branch containing `community `implementation
2. Run the following query:
```
query {
  ecoverse {
    host {
      groups {
        name
      }
    }
  }
}

```
3. The result should return groups, but instead, it returns error:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/740523a3-5447-4761-93b3-340d22f1ff8d)

**Expected behavior**
Querying host groups, should return the groups.

**Comment by techsmyth** [comment]
Fixed in the following commit:
https://github.com/cherrytwist/Server/pull/821/commits/e9bd9bdd815ebe131868b7c5f44b2607ee4f7a44
