### ISSUE TITLE
Version increment handling

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#85]
## Description
As a release manager I want to have control over when version numbers are adjusted so that we have a clear release history

## Acceptance criteria

- [ ] ...
- [ ] …

## Additional Context
Look at https://docs.npmjs.com/cli/version

**Comment by atstoyanov** [comment]
## Incrementing version manually in code is dangerous. 
During the PR another PR with same or greater version could be merged and the version in the current PR should be incremented manually. This could require incrementing several times during the PR is completed and is not error proof.

## Incrementing version should be automatically

- major - release that includes breaking changes
- minor - release that includes new features
- patch - release that includes only fug fixes and new features are not added. (critical bug fix, several bug fixes etc.).
- prerelease - (1.0.0-alpha.0, 1.0.0-alpha.1, 1.0.0-beta.\*, 1.0.0-rc.\*)  - after code freeze and during release polishing. New features can not be added after entering this phase.

Major, minor and patch should be updated semi-automatically or using special release scripts.

- build version - This information is required for identifying which build is deployed on different environments and racing the build back to the source code. It is not stored in the `package.json` and tag is not added to git<sup>1</sup>. It is visible in the build system and on the deployed environment<sup>2</sup>. Might be included in the Docker tag. Possible variants:
- tag/label in the format: 'YYYYMMDD.#' where `YYYY` is current year, `MM` is current month with leading 0, `DD` is current day with leading 0, "#" the build for that day
- build counter
- commit hash


<sup>1</sup> adding tags for each build in git makes the repository looks ugly and at some point the number of tags will be unmaintainable. Including the commit hash in the build seems better solution.
<sup>2</sup> GraphQL query that returns the back-end version will be useful for QAs and support.
