### ISSUE TITLE
BUG: Application can be approved only if it is against ecoverse community

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#858]
**Describe the bug**
Application can be approved only if it is against ecoverse community. 
In the application is created against community of challenge, error is thrown for `approveApplication`

**To Reproduce**
1. Go to `/graphql`
2. Create a challenge and get its `communityId`:
```
mutation CreateChallenge($challengeData: ChallengeInput!) {
              createChallenge(challengeData: $challengeData) {
                name
                id
                textID
                community {
                  id
                  groups {
                    id
                    name
                  }
                }               
              }
            }
```
```
{
    "challengeData": {
        "name": "test chalwleangaaaas ",
        "textID": "testcha-tae1aaas"
    }
}
```
2. Create a user and get its `userId`
```
mutation CreateUser($userData: UserInput!) {
    createUser(userData: $userData) {
      id
      name
      firstName
      lastName
      email
      phone
      city
      country
      gender
      accountUpn
    memberof{communities{id name groups{name id}}}
    }
}
```
```
{
    "userData": {
        "name": "1user12d11a",
        "firstName": "testasaFN1",
        "lastName": "tessataLN",
        "email": "1user{{unidquae1TextId}}1@test.com",
        "city": "testCity",
        "country": "testCountry",
        "gender": "testGender",
        "aadPassword": "sjk!!675&^*GAFDGFSsdfh",
        "accountUpn": "test",
        "profileData": {
            "avatar": "test",
            "description": "test"
        }
    }
}
```
3. Create application using the communityId from `createChallenge` response and get the `applicationId`
```
mutation createApplication($communityId:Float!, $applicationData: ApplicationInput!) {
  createApplication(communityID:$communityId, applicationData:$applicationData){
    id
	  questions {
      id
      name
      value
    }
    status
  }
}
```
```
{
  "communityId": 2,
  "applicationData": {
    "userId": 11,
    "questions": [
      {"name": "Test Question 1", "value": "Test answer"}
    ]
  }
}
```
4. Approve the application
```
mutation approveApplication($ID: Float!) {
  approveApplication(ID: $ID){
    id    
    status
    user{id name}
  }
}
```
```
{
  "ID": 2
}
```

The result is - error message  `"message": "User (12) is not a member of parent community: Ecoverse",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/014a9d41-f1c7-4c6e-89a0-00bbe21bf2fd)

**Expected behavior**
Application for user must be possible to be approved for communities on all entity levels (ecoverse, challenge, opportunity)

**Comment by techsmyth** [comment]
Issue is actually earlier: it should not be possible to create an application for the challenge as the user is not a member of the ecoverse.

**Comment by Comoque1** [comment]
> Issue is actually earlier: it should not be possible to create an application for the challenge as the user is not a member of the ecoverse.

Even if the user is member of a group from the ecoverse, the error is thrown - invalid statement (tested with wrong groupId :))
Don't we target the possibility for user to apply only for an entity instead to the whole hierarchy?

Example:
Create application only to specific opportunity or challenge.
