### ISSUE TITLE
BUG: User not part of ecoverse, doesn't have right to update its profile

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#866]
**Describe the bug**
User not part of ecoverse, doesn't have right to update its profile.

**To Reproduce**
1. Go to https://dev.cherrytwist.org/graphql
2. Get the token for user: non-ecoverse@cherrytwist.com
3. Use it in the following mutation:
```
mutation updateProfile($profileData: ProfileInput!, $ID: Float!) {
      updateProfile(profileData: $profileData, ID: $ID)}
```
```
{
    "ID": 58,
    "profileData": {
      "description": "123",
      "avatar": "https://avatar.com",
      "referencesData": {
        "name": "xxx",
        "description": "000"
      }
    }
  }
```
4. User is forbidden to perform update to its profile.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0eb35e3b-125a-42b6-800c-91ac1ff14990)

**Expected behavior**
User not part of ecoverse, must have right to update its profile.

**Comment by techsmyth** [comment]
Interesting one...

A user *can* update their own profile via the updateUser mutation - they just cannot invoke the updateProfile method, they have to go via the updateUser mutation. Not sure we should fix this one, and it is not easy.
