### ISSUE TITLE
Logging capability inside Server

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#89]
## Description
As a developer I want to have robust + flexible logging that I can configure at runtime so that I can get insight into what is happening on the server at multiple levels of granularity.

## Acceptance criteria

- [ ] Chosen logging package (Winston) integrated with console / file output
- [ ] Agreed set of initial logging areas e.g. authentication, api usage, system (bootstrap etc)
- [ ] Existing logging updated to use the new logging areas

## Logging package requirements
- [ ] Different levels of logging supported
- [ ] Different outputs supported / easily extensible. 
- [ ] Easy integration with Kibana
- [ ] Different outputs for different log levels
- [ ] Log rolling for files
- [ ] Different categories
- [ ] Well documented

## Additional Context
After a quick scan by usage:
- loglevel - 9m weekly downloads - very basic implementation
- winston - 5m weekly downloads
- log4js - 2m weekly downloads
- bunyan - 1m weekly downloads

Good articles on the subject:
https://www.loggly.com/blog/a-benchmark-of-five-node-js-logging-libraries/
https://www.npmtrends.com/log4js-vs-loglevel-vs-winston
https://developer.ibm.com/technologies/node-js/tutorials/learn-nodejs-winston/
https://npmcompare.com/compare/bunyan,log4js,winston

**Comment by atstoyanov** [comment]
With the introduction of logging capabilities the eslint rule for not using console.* should be enforced.
Default logging output for development should be set to console. 
The logging should be configurable.
