### ISSUE TITLE
BUG: Update user request is failing

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#895]
**Describe the bug**
Update user request is failing.

**To Reproduce**
Precondition: set `authEnabled:true` in .env file.
1. Go to https://dev.cherrytwist.org/graphql
2. Perform the following mutation:
```
mutation UpdateUser($userData: UpdateUserInput!) {
  updateUser(userData: $userData) {
    name,
  	email
  }
}
```
```
{
  "userData":
  {
    "ID": "31",
    "name": "k"
  }
}
```
3. Error is thrown: `"message": "Cannot read property 'toLowerCase' of undefined"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3b06b5c9-ce55-4689-8ba9-5aa6183d46ab)

**Expected behavior**
User must be updated successfully.

**Comment by techsmyth** [comment]
Not reproducible for me using a local instance...

**Comment by Comoque1** [comment]
> Not reproducible for me using a local instance...

Should have `authEnabled:true` in .env file.
