### ISSUE TITLE
BUG: Community-admin user doesn't have rights to create organisation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#896]
**Describe the bug**
Community-admin user doesn't have rights to create organisation.

**To Reproduce**
1. Go to https://dev.cherrytwist.org/graphql
2. Authenticate with communityAdmin user
3. Perform "createOrganisation" mutation
4. Error is thrown, that the user forbidden to perform the request

**Expected behavior**
Community admin, must be able to create organisation.

## Note:
Verification could be made by running the tests for community admin
`npm run-script test:it ./test/non-functional/auth/community-admin-user.it-spec.ts `

**Comment by techsmyth** [comment]
Fixed in authorization-engine branch, can you please re-test?

**Comment by Comoque1** [comment]
The scenario is tested and works fine.

The rest of the tests from the suite, will be run, ones they are updated.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/97044edd-7cce-4677-a85f-04dcc9981903)
