### ISSUE TITLE
BUG: Creation of second ecoverse throws an error

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#959]
**Describe the bug**
Creation of second ecoverse throws an error.

**To Reproduce**
1. Go to http://localhost:4000/graphql
2. Perform the following mutation
```
mutation CreateEcoverse($ecoverseData: CreateEcoverseInput!) {
  createEcoverse(ecoverseData: $ecoverseData) {
    name,
    id
  }
}
```
```
{
  "ecoverseData":
  {
    "name": "Test ecoverse222",
    "textID": "eco22"
  }
}
```
3. Error is thrown: `"message": "Organisation with the provided name already exists: Default host organisation"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d03477e7-5402-4bae-8fb3-9a45f92ab3bc)

**Expected behavior**
Second ecoverse, must be created successfully

**Comment by techsmyth** [comment]
Fixed in domain-model PR
