### ISSUE TITLE
BUG: Update challenge is not working

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/server#997]
**Describe the bug**
When a user intend to update a challenge, the returned results is the same as the one before the update.

**To Reproduce**
1. Go to http://localhost:4000/graphql
2. Performa the following mutation
```
mutation UpdateChallenge($challengeData: UpdateChallengeInput!) {
  updateChallenge(challengeData: $challengeData) {
    id
    name
  }
}

```
```
{
  "challengeData":
    {
      "ID": "2",
      "name": "2176123576211273"      
    }
  }
```
3. After performing the update the name remains the same.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5b972ac4-78f6-4ebe-9d27-8e4219b0a562)

**Expected behavior**
After updating an challenge, the changes must be preserved.

**Comment by techsmyth** [comment]
Just tested on develop and it is workign fine...

**Comment by Comoque1** [comment]
Not reproducible on dev env.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ab916ca4-7880-4671-9b2e-f0975f102b4a)
